[package]
name = "dark-forest"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
df-types = { path = "../df-types" }
df-contracts = { path = "../df-contracts" }
df-engine = { path = "../df-engine" }
